### ISSUE TITLE
Refactor reconcling and CRD

### ISSUE THREAD

**Issue by AhmedGrati** [AhmedGrati/kube-node-labeler#13]
# Description
The update of the CRD is basically meant to consider only adding attributes. Merging attributes won't be considered anymore.
The reason behind that is due to the fact that when we delete the CRD we could not roll back to the previous state of the merged attributes, since we don't store the state of these attributes.
Maybe it could be reconsidered in the future by implementing a more sophisticated solution but for now, it won't be supported.
In addition to that, attributes should be updated, in a way that we offer the user to have more customization over the attribute. e.g: he could specify whether to overwrite duplicate for the specific attribute or not.
```yaml
spec:
  attributes:
  - annotations:
     - annot1: true
        overwriteDuplicate: false
```
